version: '3'
services:
  shrty:
    build: ./
    container_name: shrty
    command: pnpm run dev --host
    links:
      - shrty-db
    environment:
      PORT: 3000
      DB_CONNECTION: shrty-db
      DB_PORT: 5432
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - ./:/shrty
    networks:
      - postgres
  shrty-db:
    build: ../database
    ports:
      - "5436:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge