version: '3'
services:
  online-energieausweis:
    build: ./
    container_name: online-energieausweis
    command: pnpm run dev --host
    links:
      - db:database
    environment:
      PORT: 3000
      DB_CONNECTION: database
      DB_PORT: 5432
      NODE_ENV: "development"
    ports:
      - 3000:3000
    volumes:
      - ./:/online-energieausweis
    networks:
      - postgres
  db:
    build: ../database
    ports:
      - "5436:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge