export default [
	{
		energietraeger: "Heizöl EL",
		einheit: "l",
		umrechnungsfaktor: 10.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.06,
		coe: 0.310,
	},
	{
		energietraeger: "Erdgas H",
		einheit: "m³",
		umrechnungsfaktor: 10.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.11,
		coe: 0.240,
	},
	{
		energietraeger: "Holz-Pellets",
		einheit: "kg",
		umrechnungsfaktor: 5.0,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Brennholz",
		einheit: "kg",
		umrechnungsfaktor: 4.1,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Flüssiggas",
		einheit: "kg",
		umrechnungsfaktor: 13.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.09,
		coe: 0.270,
	},
	{
		energietraeger: "Braunkohle",
		einheit: "kg",
		umrechnungsfaktor: 5.5,
		primärenergiefaktor: 1.2,
		heizwertfaktor: 1.07,
		coe: 0.430,
	},
	{
		energietraeger: "Holzhackschnitzel",
		einheit: "SRm",
		umrechnungsfaktor: 650.0,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Strommix",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 2.4,
		heizwertfaktor: 1.00,
		coe: 0.560,
	},
	{
		energietraeger: "Fernwärme KWK FB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.7,
		heizwertfaktor: 1.00,
		coe: 0.300,
	},
	{
		energietraeger: "Nahwärme KWK FB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.7,
		heizwertfaktor: 1.00,
		coe: 0.300,
	},
	{
		energietraeger: "Heizöl EL",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.06,
		coe: 0.310,
	},
	{
		energietraeger: "Erdgas H",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.11,
		coe: 0.240,
	},
	{
		energietraeger: "Holz-Pellets",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Brennholz",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Flüssiggas",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.09,
		coe: 0.270,
	},
	{
		energietraeger: "Braunkohle",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.2,
		heizwertfaktor: 1.07,
		coe: 0.430,
	},
	{
		energietraeger: "Holzhackschnitzel",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Flüssiggas",
		einheit: "l",
		umrechnungsfaktor: 7.3,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.09,
		coe: 0.270,
	},
	{
		energietraeger: "Brennholz",
		einheit: "m³",
		umrechnungsfaktor: 2000.0,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Flüssiggas",
		einheit: "m³",
		umrechnungsfaktor: 26.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.09,
		coe: 0.270,
	},
	{
		energietraeger: "Erdgas L",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.11,
		coe: 0.240,
	},
	{
		energietraeger: "Brennholz",
		einheit: "SRm",
		umrechnungsfaktor: 800.0,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Koks",
		einheit: "kg",
		umrechnungsfaktor: 8.3,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.02,
		coe: 0.400,
	},
	{
		energietraeger: "Erdgas L",
		einheit: "m³",
		umrechnungsfaktor: 9.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.11,
		coe: 0.240,
	},
	{
		energietraeger: "Koks",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.02,
		coe: 0.400,
	},
	{
		energietraeger: "Holzhackschnitzel",
		einheit: "kg",
		umrechnungsfaktor: 3.8,
		primärenergiefaktor: 0.2,
		heizwertfaktor: 1.08,
		coe: 0.020,
	},
	{
		energietraeger: "Nahwärme HKW EB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.1,
		heizwertfaktor: 1.00,
		coe: 0.060,
	},
	{
		energietraeger: "Nahwärme HKW FB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.3,
		heizwertfaktor: 1.00,
		coe: 0.400,
	},
	{
		energietraeger: "Nahwärme KWK EB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.0,
		heizwertfaktor: 1.00,
		coe: 0.040,
	},
	{
		energietraeger: "Fernwärme KWK EB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.0,
		heizwertfaktor: 1.00,
		coe: 0.040,
	},
	{
		energietraeger: "Fernwärme HKW FB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.3,
		heizwertfaktor: 1.00,
		coe: 0.400,
	},
	{
		energietraeger: "Fernwärme HKW EB",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 0.1,
		heizwertfaktor: 1.00,
		coe: 0.060,
	},
	{
		energietraeger: "Erdgas",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.11,
		coe: 0.240,
	},
	{
		energietraeger: "Heizöl",
		einheit: "kWh",
		umrechnungsfaktor: 1.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.06,
		coe: 0.310,
	},
	{
		energietraeger: "Heizöl",
		einheit: "l",
		umrechnungsfaktor: 10.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.06,
		coe: 0.310,
	},
	{
		energietraeger: "Erdgas",
		einheit: "m³",
		umrechnungsfaktor: 9.0,
		primärenergiefaktor: 1.1,
		heizwertfaktor: 1.11,
		coe: 0.240,
	},
];
