export const hotWaterProductionTypes = [
	"Konstanttemperatur-Kessel bis 1986",
	"Konstanttemperatur-Kessel von 1987 bis 1994",
	"Konstanttemperatur-Kessel ab 1995",
	"Niedertemperatur-Kessel bis 1986",
	"Niedertemperatur-Kessel von 1987 bis 1994",
	"Niedertemperatur-Kessel ab 1995",
	"Brennwert-Kessel bis 1986",
	"Brennwert-Kessel von 1987 bis 1994",
	"Brennwert-Kessel ab 1995",
	"Brennwertkessel verbessert ab 1999",
	"Elektro-Wärmepumpe (Außenluft) ab 1995",
	"Elektro-Wärmepumpe (Erdreich) von 1979 bis 1994",
	"Elektro-Wärmepumpe (Erdreich) ab 1995",
	"Elektro-Wärmepumpe (Grundwasser) ab 1995",
	"Fernwärme-Übergabestation",
	"zentraler elektrischer Speicher",
	"gasbefeuerter Speicher",
	"Therme (Umlaufwasserheizer) bis 1994",
	"Therme (Umlaufwasserheizer) ab 1995",
	"Brennwert-Therme ab 1995",
	"dezentraler elektrischer Kleinspeicher",
	"dezentraler elektrischer Durchlauferhitzer",
	"dezentraler Gas-Durchlauferhitzer bis 1994",
	"dezentraler Gas-Durchlauferhitzer ab 1995",
	"Elektro-Wärmepumpe (Außenluft) von 1979 bis 1994",
	"Elektro-Wärmepumpe (Grundwasser) von 1979 bis 1994"
]