export const buildingTypes = [
	"Hotels ohne Stern, Pensionen, Gasthäuser, Hotels garni",
	"Hotels mit 1 und 2 Sternen",
	"Hotels mit 3 Sterne",
	"Hotels mit 4 und 5 Sternen",
	"Gästehäuser, Vereinsheime",
	"Studentenwohnheime",
	"Ausschankwirtschaft",
	"Speisegaststätte/Restaurant",
	"Kantinen/Mensen",
	"Kino",
	"Opernhäuser, Theatergebäude",
	"Saalbauten, Stadthallen",
	"Spielcasinos",
	"Freizeitzentren, Jugendhäuser, Gemeindehäuser",
	"Sporthallen",
	"Mehrzweckhallen",
	"Schwimmhallen, Hallenbäder",
	"Sportheim (Vereinsheim)",
	"Handel Non-food bis 300 qm",
	"Handel Non-food bis 2000 qm",
	"Handel Food bis 300 qm",
	"Handel Food bis 2000 qm",
	"Kaufhäuser, Warenhäuser, Einkaufszentren über 2000 qm",
	"Krankenhäuser bis 250 Betten",
	"Krankenhäuser von 251 bis 450 Betten",
	"Krankenhäuser von 451 bis 650 Betten",
	"Krankenhäuser von 651 bis 1000 Betten",
	"Krankenhäuser mit über 1000 Betten",
	"Flughafen, Terminal",
	"Flughafen, Frachthallen",
	"Flughafen, Wartung/Hangar",
	"Flughafen, Werkstätten",
	"Tiefgaragen, Parkhäuser",
	"Bürogebäude, nur beheizt",
	"Bürogebäude, temperiert, mech. belüftet",
	"Bürogebäude mit Vollklimaanlage",
	"Parlamentsgebäude",
	"Gerichtsgebäude < 3.500",
	"Gerichtsgebäude > 3.500",
	"Verwaltungsgebäude < 3.500",
	"Verwaltungsgebäude > 3.500",
	"Ministerien",
	"Ämtergebäude < 3.500",
	"Ämtergebäude > 3.500",
	"Krankenkassengebäude, Rathäuser, Sozialämter",
	"Finanzämter < 3.500",
	"Finanzämter > 3.500",
	"Verwaltungsgebäude mit höherer techn. Ausstattung1",
	"Polizeidienstgebäude < 3.500",
	"Polizeidienstgebäude > 3.500",
	"Polizeiinspektionen, Kommissariate, Kriminalämter, Reviere < 3.500",
	"Polizeiinspektionen, Kommissariate, Kriminalämter, Reviere > 3.500",
	"Zollämter, -Stationen, Grenzabfertigung",
	"Rechenzentren",
	"Gebäude für wissenschaftliche Lehre",
	"Hörsaalgebäude",
	"Institutsgebäude für Lehre und Forschung < 3.500",
	"Institutsgebäude für Lehre und Forschung > 3.500",
	"Institutsgebäude I < 3.500",
	"Institutsgebäude I > 3.500",
	"Institutsgebäude II *",
	"Institutsgebäude III *",
	"Institutsgebäude IV *",
	"Institutsgebäude V *",
	"Institutsgebäude für Forschung und Untersuchung",
	"Fachhochschulen",
	"Gebäude des Gesundheitswesens",
	"Krankenhäuser und Unikliniken für Akutkranke",
	"Schulen < 3.500",
	"Schulen > 3.500",
	"Allgemeinbildende Schulen < 3.500",
	"Allgemeinbildende Schulen > 3.500",
	"Grundschulen < 3.500",
	"Grundschulen > 3.500",
	"Hauptschulen",
	"Realschulen",
	"Gymnasien",
	"Gesamtschulen",
	"Berufsbildende Schulen < 3.500",
	"Berufsbildende Schulen > 3.500",
	"Sonderschulen",
	"Kindertagesstätten",
	"Weiterbildungseinrichtungen",
	"Sportbauten",
	"Hallen (ohne Schwimmhallen)",
	"Schwimmhallen",
	"Gebäude für Sportplatz- und Freibade anlagen",
	"Gebäude für Freibadeanlagen einschl. Außenanlagen",
	"Gemeinschaftsstätten < 3.500",
	"Gemeinschaftsstätten > 3.500",
	"Gemeinschaftsunterkünfte",
	"Betreuungseinrichtungen",
	"Gaststätten",
	"Mensen",
	"Beherbergungsstätten",
	"Gebäude für Produktion, Werkstätten, Lagergebäude < 3.500",
	"Gebäude für Produktion, Werkstätten, Lagergebäude > 3.500",
	"Land- und forstwirtschaftliche Produktionsstätten",
	"Verkaufsstätten",
	"Betriebs- und Werkstätten",
	"Gebäude für Lagerung",
	"Garagengebäude",
	"Gebäude für öffentliche Bereitschaftsdienste < 3.500",
	"Gebäude für öffentliche Bereitschaftsdienste > 3.500",
	"Straßenmeistereien",
	"Bauhöfe",
	"Feuerwehren",
	"THW-Höfe",
	"Bauwerke für technische Zwecke",
	"Gebäude für kulturelle und musische Zwecke < 3.500",
	"Gebäude für kulturelle und musische Zwecke > 3.500",
	"Ausstellungsgebäude",
	"Bibliotheksgebäude",
	"Veranstaltungsgebäude",
	"Gemeinschaftshäuser",
	"Justizvollzugsanstalten",
];
