name: Node.js CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: "212.227.45.4"
        username: "root"
        password: "M!q@f8pJK&"
        port: 22
        script: |
          cd ~/shrty/
          git pull origin main
          git status
          pnpm install --prod
          pnpm run build
          bash launch.bash
